Massive Update
agentdid127/RPC-Bedrock pull request #12
Opened 2024-04-08 23:05 UTC by enqorman

Basically redid everything, and added tons of new converters/fixes.

2024-04-09 00:58 UTC, CoryBorek requested changes

2024-04-09 00:58 UTC, CoryBorek commented on bedrock-conversion/src/main/java/com/agentdid127/resourcepack/bedrock/BedrockPackConverter.java
> +		gsonBuilder.disableHtmlEscaping();
Duplicate line

2024-04-09 00:58 UTC, CoryBorek commented on bedrock-conversion/src/main/java/com/agentdid127/resourcepack/bedrock/Util.java
> +public final class Util {
Is this file in a dependency jar?

2024-04-09 00:58 UTC, CoryBorek commented on bedrock-conversion/src/main/java/com/agentdid127/resourcepack/bedrock/impl/PackMetaConverter.java
> +			minVersion.add(16);
We need to make sure that this is the actual min supported version

2024-04-09 00:58 UTC, CoryBorek commented on bedrock-conversion/src/main/java/com/agentdid127/resourcepack/bedrock/impl/PurgerConverter.java
> +    }
Is there an actual use to this? Just printing doesn't make a ton of sense.

2024-04-09 15:18 UTC, enqorman reviewed
fixed

2024-04-10 20:30 UTC, CoryBorek approved these changes

2024-04-10 20:30 UTC, merged